// seed.js — Run with: node seed.js
require('dotenv').config();
const mongoose = require('mongoose');
const Job      = require('./models/Job');

const jobs = [
  { title:"Senior Frontend Engineer", company:"Stripe", location:"San Francisco, CA", type:"Full-time", salary:"$160k – $200k", tags:["React","TypeScript","GraphQL"], logo:"S", color:"#6772e5", postedAt:"2d ago", description:"Join Stripe's web platform team to build the financial infrastructure of the internet. You'll work on high-impact, user-facing products used by millions of developers worldwide.", requirements:["5+ years React experience","TypeScript proficiency","Experience with design systems","Strong web performance mindset"], benefits:["Equity package","Remote-friendly","Unlimited PTO","$3k learning budget"] },
  { title:"Backend Engineer – Infra", company:"Vercel", location:"Remote", type:"Full-time", salary:"$140k – $180k", tags:["Node.js","Rust","Kubernetes"], logo:"V", color:"#232323", postedAt:"1d ago", description:"Help us build the world's fastest frontend cloud. Work on deployment pipelines, edge functions, and infrastructure powering millions of websites.", requirements:["Node.js / Rust / Go experience","Distributed systems knowledge","Kubernetes & Docker","CI/CD expertise"], benefits:["100% remote","Top-tier health insurance","Annual team retreats","Latest MacBook Pro"] },
  { title:"Product Designer", company:"Figma", location:"New York, NY", type:"Full-time", salary:"$130k – $160k", tags:["UI/UX","Figma","Prototyping"], logo:"F", color:"#f24e1e", postedAt:"3d ago", description:"Design the next generation of collaborative tools shaping how millions of designers and developers work every day.", requirements:["4+ years product design","Expert Figma user","Strong visual portfolio","User research experience"], benefits:["Creative culture","Design conference budget","Figma Pro free","Flexible hours"] },
  { title:"ML Engineer", company:"Hugging Face", location:"Paris, France", type:"Full-time", salary:"$150k – $190k", tags:["Python","PyTorch","LLMs"], logo:"H", color:"#ff9d00", postedAt:"5d ago", description:"Work at the frontier of open-source AI. Build tools the ML community uses to train, share, and deploy cutting-edge models.", requirements:["ML/DL deep expertise","PyTorch or TensorFlow","Distributed training experience","Research publications preferred"], benefits:["Open-source first","Remote-first","Research time budget","Top AI community"] },
  { title:"DevOps Engineer", company:"Datadog", location:"Austin, TX", type:"Full-time", salary:"$135k – $165k", tags:["AWS","Terraform","Python"], logo:"D", color:"#774aa4", postedAt:"1w ago", description:"Build and maintain infrastructure handling billions of metrics per second. Work on reliability, automation, and scale.", requirements:["AWS / GCP expertise","Terraform & IaC","Strong Python scripting","SRE mindset"], benefits:["Stock options","Home office stipend","Gym membership","Performance bonus"] },
  { title:"iOS Engineer", company:"Notion", location:"Remote", type:"Full-time", salary:"$145k – $175k", tags:["Swift","SwiftUI","iOS"], logo:"N", color:"#1a1a1a", postedAt:"2d ago", description:"Build Notion's mobile experience for millions of users. Create a seamless, delightful iOS product.", requirements:["Swift & SwiftUI mastery","Deep iOS SDK knowledge","App Store deployment","Performance profiling"], benefits:["Fully remote","Generous equity","Annual offsites","Notion Pro subscription"] },
  { title:"Data Analyst", company:"Airbnb", location:"Seattle, WA", type:"Contract", salary:"$90k – $120k", tags:["SQL","Python","Tableau"], logo:"A", color:"#ff5a5f", postedAt:"4d ago", description:"Turn data into decisions at global scale. Partner with teams to understand user behavior and improve the Airbnb experience.", requirements:["SQL mastery","Python / R","Tableau or Looker","Excellent communication"], benefits:["Travel credits","Contract-to-hire potential","Collaborative culture","Competitive rate"] },
  { title:"Security Engineer", company:"Cloudflare", location:"Austin, TX", type:"Full-time", salary:"$155k – $185k", tags:["Security","Rust","Go"], logo:"C", color:"#f6821f", postedAt:"6d ago", description:"Help secure infrastructure protecting millions of websites. Work on threat detection and security tooling at internet scale.", requirements:["Security engineering expertise","Vulnerability research","Rust or Go proficiency","Network security depth"], benefits:["Work from anywhere","Conference budget","Security tools stipend","Industry-best benefits"] },
  { title:"Frontend Developer", company:"Linear", location:"Remote", type:"Part-time", salary:"$80k – $100k", tags:["React","CSS","Animation"], logo:"L", color:"#5e6ad2", postedAt:"3d ago", description:"Help craft the most beautifully designed project management tool. Work on UI performance and micro-details that make Linear magical.", requirements:["React deep expertise","Advanced CSS","Animation & motion","Obsessive attention to detail"], benefits:["Part-time flexibility","Fully remote","Annual tool budget","Equity options"] },
  { title:"Full Stack Engineer", company:"Linear", location:"Remote", type:"Full-time", salary:"$130k – $160k", tags:["React","Node.js","PostgreSQL"], logo:"L", color:"#5e6ad2", postedAt:"1d ago", description:"Build full-stack features end-to-end on the fastest growing developer tool. Own entire features from database to UI.", requirements:["React + Node.js expertise","PostgreSQL & database design","API design experience","Product thinking"], benefits:["Fully remote","Top-tier equity","Team offsites","No meeting Fridays"] },
  { title:"Android Engineer", company:"Spotify", location:"Stockholm, Sweden", type:"Full-time", salary:"$120k – $155k", tags:["Kotlin","Android","Jetpack Compose"], logo:"S", color:"#1db954", postedAt:"2d ago", description:"Build the music app used by 600M+ people. Work on streaming, offline playback, and a world-class Android experience.", requirements:["Kotlin & Jetpack Compose","Android performance tuning","Media playback experience","Strong architecture skills"], benefits:["Free Spotify Premium","Flexible working","Annual wellness allowance","Stock program"] },
  { title:"Backend Engineer", company:"Shopify", location:"Remote", type:"Full-time", salary:"$135k – $170k", tags:["Ruby","Rails","GraphQL"], logo:"S", color:"#96bf48", postedAt:"5d ago", description:"Power commerce for millions of merchants. Build the APIs and services that enable billions of dollars in transactions daily.", requirements:["Ruby on Rails expertise","GraphQL API design","High-scale systems","Merchant-focused product thinking"], benefits:["All-remote company","Digital nomad program","Generous parental leave","Annual stipend"] },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    await Job.deleteMany({});
    await Job.insertMany(jobs);
    console.log(`✅ Seeded ${jobs.length} jobs into MongoDB!`);
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
    process.exit(1);
  }
}
seed();
